package com.musiclib.core.extractor.services.youtube.extractors.kiosk;

import com.musiclib.core.extractor.StreamingService;
import com.musiclib.core.extractor.downloader.Downloader;
import com.musiclib.core.extractor.exceptions.ExtractionException;
import com.musiclib.core.extractor.exceptions.ParsingException;
import com.musiclib.core.extractor.exceptions.UnsupportedContentInCountryException;
import com.musiclib.core.extractor.services.youtube.StringObfuscator;
import com.musiclib.core.extractor.linkhandler.ListLinkHandler;

import javax.annotation.Nonnull;
import java.io.IOException;

public class YoutubeTrendingMusicExtractor extends YoutubeChartsBaseKioskExtractor {

    public YoutubeTrendingMusicExtractor(final StreamingService streamingService,
                                         final ListLinkHandler linkHandler,
                                         final String kioskId) {
        super(streamingService, linkHandler, kioskId, "TRENDING_VIDEOS");
    }

    @Override
    public void onFetchPage(@Nonnull final Downloader downloader)
            throws IOException, ExtractionException {
        if (!YT_CHARTS_SUPPORTED_COUNTRY_CODES.contains(
                getExtractorContentCountry().getCountryCode())) {
            throw new UnsupportedContentInCountryException(
                    StringObfuscator.decode(new int[]{7, 49, 43, 10, 43, 60, 59, 126, 29, 54, 63, 44, 42, 45, 126, 58, 49, 59, 45, 48, 121, 42, 126, 45, 43, 46, 46, 49, 44, 42, 126, 42, 54, 55, 45, 126, 61, 49, 43, 48, 42, 44, 39, 126, 56, 49, 44, 126, 42, 44, 59, 48, 58, 55, 48, 57, 126, 51, 43, 45, 55, 61, 126, 40, 55, 58, 59, 49, 45, 126, 61, 54, 63, 44, 42, 45}));
        }
        super.onFetchPage(downloader);
    }

    @Nonnull
    @Override
    public String getName() throws ParsingException {
        // This is the official YouTube Charts name, even if autogenerated tracks and unofficial
        // contents are returned
        return "Trending Music Videos";
    }
}
